### ISSUE TITLE
list of yoga poses

### ISSUE THREAD

**Issue by antoniatandler** [antoniatandler/capstone-project#1]
# PosesList

## Value proposition
- As a Yogi
- I want to view a list of poses
- in order to decide which one I want to practice

## Description
<img width="336" alt="Bildschirmfoto 2023-05-17 um 22 32 21" src="https://github.com/antoniatandler/capstone-project/assets/128368770/458a1880-fe97-4b39-bf48-c54b3b3b86b5">

## Acceptance criteria
- [x] List scrolls vertically
- [x] Listitem height is as high as content
- [x] The heading is always visible

## Tasks
- [x] create Heading Component and include
- [x] Fetch data from https://yoga-api-nzy4.onrender.com/v1
- [x] Save data in a state
- [x] create ListOfYogaPoses Component and include
- [x] map over fetched data to create List and display fetched data
