### ISSUE TITLE
searchbar 

### ISSUE THREAD

**Issue by antoniatandler** [antoniatandler/capstone-project#13]
# searchbar

## Value proposition
- As a yogi
- i would like to have the ability to search for specific yoga poses
- to get only these displayed

## Description
<img width="621" alt="Bildschirmfoto 2023-06-13 um 15 19 02" src="https://github.com/antoniatandler/capstone-project/assets/128368770/7f199158-bc7d-4041-8c56-c6588f24783d">

## Acceptance criteria
- [ ] searchbar is visible and usable
- [ ] handles input and displays poses that fit to the searchinput

## Tasks
- [ ] Create branch "serachfunction"
- [ ] Create Search Input Field
- [ ] Create Handle Function
