### ISSUE TITLE
bookmarks

### ISSUE THREAD

**Issue by antoniatandler** [antoniatandler/capstone-project#14]
# Bookmarks

## Value proposition
- As a yogi
- I want to set bookmarks on my favourite poses
- in order to save them on an extra page and see them quicker

## Description
<img width="732" alt="Bildschirmfoto 2023-06-13 um 15 36 04" src="https://github.com/antoniatandler/capstone-project/assets/128368770/c2d61318-84b0-4516-ba6a-f81bb2622243">

## Acceptance criteria
- [x] bookmarks change color when clicked
- [x] clicked bookmarked poses are shown on the page "bookmarks"
- [x] the dropdown menu shows the section "bookmarks" too

## Tasks
- [x] Create branch "bookmarks"
- [x] Create Bookmark Component
- [x] Create bookmarks.js and display bookmarked poses
- [x] implement bookmarks to hamburger menu nav

**Comment by MerleMak** [comment]
you will probably want to create a bookmarks.js as a page :)
Other than that, great! Excited to see it🚀

**Comment by MariaRiosNavarro** [comment]
i can not find the page "bookmarks" but the bookmarks change color work
