### ISSUE TITLE
details page

### ISSUE THREAD

**Issue by antoniatandler** [antoniatandler/capstone-project#2]
# Details Page

## Value proposition
- As a Yogi
- I want to choose one yogapose from the list (repeatedly with different poses and successively)
- in order to see more details and the description of it

## Description
<img width="268" alt="Bildschirmfoto 2023-05-17 um 23 22 43" src="https://github.com/antoniatandler/capstone-project/assets/128368770/ee9ad646-186f-4104-8ad3-8f87a4e9098d">

## Acceptance criteria
- [ ] the "back to all button" works
- [ ] the names, image, description and benefits of the clicked pose are displayed as a card

## Tasks
- [ ] create pose-model
- [ ] create yogapose-component and import pose-model
- [ ] display the details on details-page
