### ISSUE TITLE
welcome page

### ISSUE THREAD

**Issue by antoniatandler** [antoniatandler/capstone-project#3]
# Welcome-Page

## Value proposition
- As a Yogi
- I want to see at first a welcome page with a pretty interface which is related to yoga and includes an overview
- in order to feel "oh, that's fine, I want to stay here" and see which features the website has 

## Description

<img width="253" alt="Bildschirmfoto 2023-05-23 um 15 52 20" src="https://github.com/antoniatandler/capstone-project/assets/128368770/71eba1d7-d78e-43d5-8e78-21b3d2222219">

## Acceptance criteria
- [x] Heading is included and always visible
- [x] there is a welcome-message which welcomes the visitor
- [x] Features are shown and ordered
- [x] Features-Overview pieces are linked to their Feature-pages (which are empty yet, will fill them in later US)

## Tasks
- [x] Create branch "welcome-page"
- [x] Create Comnponent for Welcome-Message and display on Welcomepage
- [x] Create Component for Feature overview and and display on Welcomepage -> create styled component for feature button (overview)
- [x] style
- [x] Link page(s)
