### ISSUE TITLE
User Story #3

### ISSUE THREAD

**Issue by antoniatandler** [antoniatandler/capstone-project#3]
# Welcome-Page

## Value proposition
- As a Yogi
- I want to see at first a welcome page with a pretty interface which is related to yoga and includes an overview
- in order to feel "oh, that's fine, I want to stay here" and see which features the website has 

## Description

<img width="244" alt="Bildschirmfoto 2023-05-23 um 15 42 47" src="https://github.com/antoniatandler/capstone-project/assets/128368770/5a45b835-8862-4de8-8535-5428451d1e39">

## Acceptance criteria
- [ ] Heading is included and always visible
- [ ] Features are shown and ordered
- [ ] Features-Overview pieces are linked to their Feature-pages (which are empty yet, will fill them in later US)

## Tasks
- [ ] Create branch "welcome-page"
- [ ] Create Overview and style
- [ ] Link pages
