### ISSUE TITLE
navbar

### ISSUE THREAD

**Issue by antoniatandler** [antoniatandler/capstone-project#4]
# Navbar

## Value proposition
- As a Yogi
- I want to have a navbar on each page
- in order to navigate through the app

## Description
<img width="244" alt="Bildschirmfoto 2023-05-23 um 16 18 33" src="https://github.com/antoniatandler/capstone-project/assets/128368770/c985250c-955f-452f-91f4-5956abf5a8b6">

## Acceptance criteria
- [ ] Heading is included and always visible
- [ ] Navbar is always visible and fixed

## Tasks
- [ ] Create branch "navbar"
- [ ] Create Comnponent Navbar
- [ ] style
- [ ] Link pages
