### ISSUE TITLE
User Story #4

### ISSUE THREAD

**Issue by antoniatandler** [antoniatandler/capstone-project#4]
# Nav-Bar

## Value proposition
- As a Yogi
- I want to see a navbar on each page
- in order to navigate through the app

## Description

<img width="244" alt="Bildschirmfoto 2023-05-23 um 16 18 33" src="https://github.com/antoniatandler/capstone-project/assets/128368770/7359d272-8a7e-42e2-bed9-9135b7f65c22">

## Acceptance criteria
- [ ] Heading is included and always visible
- [ ] Navbar is always shown and styled

## Tasks
- [ ] Create branch "navbar"
- [ ] Create Navbar-Component
- [ ] Display Navbar
- [ ] Import Navbar-Component to all pages

**Comment by MerleMak** [comment]
This looks like it would be useful for the Desktop version of your app :) for a mobile version, you could look into "Hamburger menus" which might be interesting as they don't take up much space. 
But you should save this for when you have all the features and time to focus on the desktop version (don't forget: mobile first, so the mobile version should work before) :)

**Comment by antoniatandler** [comment]
aaaah yes, of course! 🤦🏻‍♀️ thank you for this hint! to be real: i did not think about that while drawing the navigation. i will update this US asap.
