### ISSUE TITLE
hamburger menue

### ISSUE THREAD

**Issue by antoniatandler** [antoniatandler/capstone-project#5]
# hamburger menue

## Value proposition
- As a Yogi
- I want to see the subitems of the navbar on each page in a small hamburger nav menue
- in order to navigate much better through the app no matter on what page I am

## Description
<img width="822" alt="Bildschirmfoto 2023-05-24 um 12 02 22" src="https://github.com/antoniatandler/capstone-project/assets/128368770/0bdae733-7948-4ea6-81c4-1a0137d5d9fc">
new: <img width="112" alt="Bildschirmfoto 2023-06-07 um 12 17 34" src="https://github.com/antoniatandler/capstone-project/assets/128368770/016d6781-451a-4618-82b9-1b1d242dddb0">

## Acceptance criteria
- [ ] Heading is included and always visible
- [ ] Hambuer menue is always shown and styled
- [ ] hamburger menue is filled with items and linked to pages

## Tasks
- [ ] Create branch "navbar-items"
- [ ] Create hambuger menue
- [ ] Import navbaritems
- [ ] Display navbaritems in dropdown menue

**Comment by HenrikeStahlhut** [comment]
Hi Antonia, 
i really like your app idea :)

Personally, i think your menu looks a bit cluttered in the wireframe. Maybe you could think about having the subfeatures directly under the features in a different color/with less opacity to differentiate them from the features? Or if you plan on having less features, a navbar at the bottom also works and looks a bit cleaner. 

That's just something to think about, but otherwise your US looks great and would be approved if you don't want to change your menu 👍🏻
