### ISSUE TITLE
reminder 

### ISSUE THREAD

**Issue by antoniatandler** [antoniatandler/capstone-project#6]
# Reminder

## Value proposition
- As a yogi
- I want to be reminded to get flexy
- in order to don't forget it and to stay with my yoga journey

## Description
<img width="326" alt="Bildschirmfoto 2023-05-24 um 12 17 24" src="https://github.com/antoniatandler/capstone-project/assets/128368770/1d728263-af1b-45f0-aa4f-608ce4cbf15b">

## Acceptance criteria
- [ ] reminder pops up at display to the by the user choosen time
- [ ] reminds the user to get flexy and suggests a random yoga pose
- [ ] if user clicks "now" the app opens and the suggested yoga pose is shown
- [ ] if user clicks "later" a pop up opens which asks when the user want to be reminded again (5min, 20min, 1hr, self adjusted)

## Tasks
- [ ] Create branch "reminder"
- [ ] Create Reminder Component
- [ ]
