### ISSUE TITLE
User Story #1 

### ISSUE THREAD

**Issue by antoniatandler** [antoniatandler/capstone-project#7]
# List of yoga poses

## Value proposition
- As a Yogi
- I want to view a list of poses
- in order to decide which one I want to practice

## Description
<img width="336" alt="Bildschirmfoto 2023-05-17 um 22 32 21" src="https://github.com/antoniatandler/capstone-project/assets/128368770/458a1880-fe97-4b39-bf48-c54b3b3b86b5">

## Acceptance criteria
- [x] List scrolls vertically
- [x] Listitem height is as high as content
- [x] The heading is always visible

## Tasks
- [x] create Heading Component and include
- [x] Fetch data from https://yoga-api-nzy4.onrender.com/v1
- [x] Save data in a state
- [x] create ListOfYogaPoses Component and include
- [x] map over fetched data to create List and display fetched data

**Comment by MerleMak** [comment]
Hi Antonia! This looks great, the only thing that I (just) noticed, is that in your wireframe there are 4 buttons on the landing page, which won't have any function. Its best to start out without that landing page and only create it once you actually created the "categories" page or "plans" page. Remember to only ever add code that has functionality behind it :)
Maybe you can add a nAcceptance Criteria (AC) for what happens if the user clicks on one of the pose-cards :)
Besides that, good job!

**Comment by HenrikeStahlhut** [comment]
As Merle said, you should only add the "all poses" button on your homepage for now, since the other buttons have no function yet. In the next user stories, you slowly add the other components to your wireframes as you code them! 
Love your app idea and happy coding 🧘🏻‍♀️

**Comment by antoniatandler** [comment]
thanks to both of you!!

 with the first picture I wanted to show which area i want to edit, but I now know that thats not the point here. So I changed this part and will include it in later user stories 😇

**Comment by MerleMak** [comment]
Great work!
